"""empty message

Revision ID: 10f875cad583
Revises: 314812516dee
Create Date: 2015-08-03 12:02:13.353313

"""

# revision identifiers, used by Alembic.
revision = '10f875cad583'
down_revision = '314812516dee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('listing', sa.Column('product_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'listing', 'product', ['product_id'], ['id'])
    op.alter_column('product', 'upc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'upc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('product', 'id')
    op.drop_constraint(None, 'listing', type_='foreignkey')
    op.drop_column('listing', 'product_id')
    ### end Alembic commands ###
