"""empty message

Revision ID: 1c66edab58a2
Revises: 10f875cad583
Create Date: 2015-08-03 12:08:50.895417

"""

# revision identifiers, used by Alembic.
revision = '1c66edab58a2'
down_revision = '10f875cad583'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'listing', 'product', ['product_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listing', type_='foreignkey')
    ### end Alembic commands ###
