"""empty message

Revision ID: 204c671629b5
Revises: 35df61b36605
Create Date: 2015-07-30 14:42:35.363163

"""

# revision identifiers, used by Alembic.
revision = '204c671629b5'
down_revision = '35df61b36605'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
