"""empty message

Revision ID: 314812516dee
Revises: 32e47a1d2e88
Create Date: 2015-08-03 11:18:59.046773

"""

# revision identifiers, used by Alembic.
revision = '314812516dee'
down_revision = '32e47a1d2e88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'image', ['tiny_image'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='unique')
    ### end Alembic commands ###
