"""empty message

Revision ID: 32e47a1d2e88
Revises: 5709ffd60192
Create Date: 2015-08-01 18:43:36.331222

"""

# revision identifiers, used by Alembic.
revision = '32e47a1d2e88'
down_revision = '5709ffd60192'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
