"""empty message

Revision ID: 35df61b36605
Revises: None
Create Date: 2015-07-30 12:28:44.784387

"""

# revision identifiers, used by Alembic.
revision = '35df61b36605'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiny_image', sa.String(), nullable=True),
    sa.Column('small_image', sa.String(), nullable=True),
    sa.Column('medium_image', sa.String(), nullable=True),
    sa.Column('large_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('listing',
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('upc', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('result_all', postgresql.JSON(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('asin')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing')
    op.drop_table('user')
    op.drop_table('image')
    ### end Alembic commands ###
