"""empty message

Revision ID: 483a9c47d7e5
Revises: 403cb553ae64
Create Date: 2015-08-20 21:46:50.064079

"""

# revision identifiers, used by Alembic.
revision = '483a9c47d7e5'
down_revision = '403cb553ae64'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_all', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    ### end Alembic commands ###
