"""empty message

Revision ID: 4a55e0ef0be1
Revises: 483a9c47d7e5
Create Date: 2015-09-08 16:23:30.045068

"""

# revision identifiers, used by Alembic.
revision = '4a55e0ef0be1'
down_revision = '483a9c47d7e5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('res_price', sa.Float(), nullable=True),
    sa.Column('com_price', sa.Float(), nullable=True),
    sa.Column('shipping', sa.Float(), nullable=True),
    sa.Column('leadtime', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('upc', sa.String(), nullable=True),
    sa.Column('fba', sa.Boolean(), nullable=True),
    sa.Column('instock', sa.Boolean(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('listing_asin', sa.String(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['listing_asin'], ['listing.asin'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('address', postgresql.JSON(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('representative', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'image', sa.Column('catalog_id', sa.Integer(), nullable=True))
    op.add_column(u'image', sa.Column('listing_asin', sa.String(), nullable=True))
    op.add_column(u'image', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'image', 'listing', ['listing_asin'], ['asin'])
    op.create_foreign_key(None, 'image', 'catalog', ['catalog_id'], ['id'])
    op.add_column(u'product', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'image', ['image_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column(u'product', 'image_id')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column(u'image', 'product_id')
    op.drop_column(u'image', 'listing_asin')
    op.drop_column(u'image', 'catalog_id')
    op.drop_table('company')
    op.drop_table('catalog')
    ### end Alembic commands ###
