"""empty message

Revision ID: 4f53b3386c86
Revises: None
Create Date: 2015-08-14 14:23:40.354938

"""

# revision identifiers, used by Alembic.
revision = '4f53b3386c86'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
