"""empty message

Revision ID: 5709ffd60192
Revises: 57b0002f2621
Create Date: 2015-07-31 19:47:05.094057

"""

# revision identifiers, used by Alembic.
revision = '5709ffd60192'
down_revision = '57b0002f2621'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('upc', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('primary_cost', sa.Float(), nullable=True),
    sa.Column('secondary_cost', sa.Float(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('width', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('upc')
    )
    op.create_foreign_key(None, 'listing', 'product', ['upc'], ['upc'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listing', type_='foreignkey')
    op.drop_table('product')
    ### end Alembic commands ###
