"""empty message

Revision ID: 57b0002f2621
Revises: 204c671629b5
Create Date: 2015-07-30 14:43:29.402722

"""

# revision identifiers, used by Alembic.
revision = '57b0002f2621'
down_revision = '204c671629b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
