"""empty message

Revision ID: a8bd27a39b5
Revises: 4a55e0ef0be1
Create Date: 2015-09-09 12:23:36.399566

"""

# revision identifiers, used by Alembic.
revision = 'a8bd27a39b5'
down_revision = '4a55e0ef0be1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
